# template, copy into env folder and change the values, then add as a patch to the kustomization.yaml file

- op: replace
  path: /spec/rules/0/host
  value: localhost
- op: replace
  path: /spec/tls/0/hosts
  value:
    - localhost
