# https://kubernetes.io/docs/concepts/configuration/secret
apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: languageforge
data:
  MONGODB_CONN: ''
  REMEMBER_ME_SECRET: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: languageforge
data:
  MONGODB_AUTHSOURCE: ''
  MONGODB_USER: ''
  MONGODB_PASS: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: ld-api
  namespace: languageforge
data:
  LANGUAGE_DEPOT_API_TOKEN: ''
  LDAPI_BASE_URL: ''
  LEX_BOX_HOST: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: ld-trust-token
  namespace: languageforge
data:
  LD_TRUST_TOKEN: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: mail
  namespace: languageforge
data:
  SMTP_PASSWORD: ''
  SMTP_SERVER: ''
  SMTP_USERNAME: ''

---

apiVersion: v1
kind: Secret
metadata:
  name: oauth
  namespace: languageforge
data:
  FACEBOOK_CLIENT_ID: ''
  FACEBOOK_CLIENT_SECRET: ''
  GOOGLE_CLIENT_ID: ''
  GOOGLE_CLIENT_SECRET: ''
