# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lfmerge
  name: lfmerge
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: lfmerge

---

# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lf-project-assets
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: weekly-snapshots-retain-4 # provided by LTOps

---

# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lfmerge-sendreceive-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: weekly-snapshots-retain-4 # provided by LTOps

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lfmerge
  name: lfmerge
spec:
  selector:
    matchLabels:
      app: lfmerge
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: lfmerge
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: sendreceive-data
        persistentVolumeClaim:
          claimName: lfmerge-sendreceive-data
      initContainers:
      - name: initialize-volume-ownership
        image: busybox:1.33
        command:
          - 'sh'
          - '-c'
          - |-
            mkdir -m 02775 -p /var/lib/languageforge/lexicon/sendreceive/state /var/lib/languageforge/lexicon/sendreceive/syncqueue /var/lib/languageforge/lexicon/sendreceive/webwork /var/lib/languageforge/lexicon/sendreceive/Templates
            chown www-data:www-data /var/lib/languageforge/lexicon/sendreceive /var/lib/languageforge/lexicon/sendreceive/state /var/lib/languageforge/lexicon/sendreceive/syncqueue /var/lib/languageforge/lexicon/sendreceive/webwork /var/lib/languageforge/lexicon/sendreceive/Templates
        volumeMounts:
          - mountPath: /var/lib/languageforge/lexicon/sendreceive
            name: sendreceive-data
      containers:
      - name: lfmerge
        image: ghcr.io/sillsdev/lfmerge:{{VERSION_LFMERGE}}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/languageforge/lexicon/sendreceive
            name: sendreceive-data
        env:
          - name: ENVIRONMENT
            value: production
          - name: LFMERGE_LOGGING_DEST
            value: syslog
          - name: LFMERGE_BASE_DIR
            value: /var/lib/languageforge/lexicon/sendreceive
          - name: LFMERGE_WEBWORK_DIR
            value: webwork
          - name: LFMERGE_TEMPLATES_DIR
            value: Templates
          - name: LFMERGE_MONGO_HOSTNAME
            value: db
          - name: LFMERGE_MONGO_PORT
            value: "27017"
          - name: LFMERGE_MONGO_MAIN_DB_NAME
            value: scriptureforge
          - name: LFMERGE_MONGO_DB_NAME_PREFIX
            value: sf_
          - name: LFMERGE_VERBOSE_PROGRESS
            value: "true"
          # TODO: Rename to LANGUAGE_DEPOT_TRUST_TOKEN
          - name: LD_TRUST_TOKEN
            valueFrom:
              secretKeyRef:
                key: LD_TRUST_TOKEN
                name: ld-trust-token
