# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: next-app
  name: next-app
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: next-app

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: next-app
  name: next-app
spec:
  selector:
    matchLabels:
      app: next-app
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: sillsdev/web-languageforge:{{VERSION}}
        imagePullPolicy: Always
        env:
          - name: API_HOST
            value: http://app
