# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: languageforge-app
  annotations:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
    # Added this to allow large file uploads, this setting should match the php custom config, i.e., upload_max_filesize, found in the app's customizations.php.ini
    nginx.ingress.kubernetes.io/proxy-body-size: 60M
spec:
  rules:
  - host: {{WEBSITE}}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: next-proxy
            port:
              number: 80
  tls:
  - hosts:
    - {{WEBSITE}}
    secretName: languageforge-tls

---

# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: next-proxy
  name: next-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: next-proxy

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: next-proxy
  name: next-proxy
spec:
  selector:
    matchLabels:
      app: next-proxy
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: next-proxy
    spec:
      containers:
      - name: next-proxy
        image: sillsdev/web-languageforge:{{VERSION}}
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
        imagePullPolicy: Always
        resources:
          requests:
            memory: 12Mi
            cpu: 0.1
          limits:
            memory: 20Mi
        env:
          - name: LEGACY_APP
            value: app:80
          - name: NEXT_APP
            value: next-app:3000
