name: Add Issues To Project Board

on: issues
  types: opened

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Add new issues to project board
        uses: dhruvkb/issue-projector@0.0.7
        with:
          ACCESS_TOKEN: ${{ github.token }}
          ORG_NAME: sillsdev
          PROJECT_NUMBER: 1
          COLUMN_NAME: Backlog
          ISSUE_TYPE: issue

