name: Publish ad-hoc image to Docker Hub

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    paths:
      - '**build-and-publish-adhoc.yml'

env:
  TAG: pr-1247

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE: sillsdev/web-languageforge:${{ env.TAG }}

    steps:
      - uses: actions/checkout@v2

      - name: combined env vars
        run: echo "IMAGE=${{ env.IMAGE }}"
      # - name: Build and tag app
      #   run: docker build -t sillsdev/web-languageforge:${{ env.TAG }} -f docker/app/Dockerfile .

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Publish image
      #   run: |
      #     docker push sillsdev/web-languageforge:${{ env.TAG }}
