name: Publish image to Docker Hub (Adhoc)

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    paths:
      - '**build-and-publish-adhoc.yml'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    env:
      TAG: pr-1247

    steps:
      - uses: actions/checkout@v2

      - name: Build and tag app
        run: docker build -t sillsdev/web-languageforge:${{ env.TAG }} -f docker/app/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish all tagged images to Docker Hub
        run: |
          docker push sillsdev/web-languageforge:${{ env.TAG }}
