name: Publish image to Docker Hub (Adhoc)

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    paths:
      - '**build-and-publish-adhoc.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: testing
        run: echo ${{ inputs }}

      # - name: Build and tag app
      #   run: docker build -t sillsdev/web-languageforge:pr-1247 -f docker/app/Dockerfile .

      # - name: Reveal images
      #   run: docker images

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Publish all tagged images to Docker Hub
      #   run: |
      #     docker push -a sillsdev/web-languageforge
