name: Publish ad-hoc image to Docker Hub

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  workflow_dispatch:
    inputs:
      # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_id
      tag:
        description: Docker tag to publish
        required: true

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    env:
      IMAGE: sillsdev/web-languageforge

    steps:
      - uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
          cache: 'npm'
      -
        run: npm install -g npm@7.6.3
      -
        run: npm install

      - name: Build and tag app
        run: docker build -t ${{ env.IMAGE }}:${{ github.event.inputs.tag }} -f docker/app/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish image
        run: |
          docker push ${{ env.IMAGE }}:${{ github.event.inputs.tag }}
