name: Deploy to Docker Hub

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set BUILD_VERSION for Production from git tag
        # define BUILD_VERSION as stripping off initial 11 characters, i.e. "refs/tags/v"
        run: |-
          echo "BUILD_VERSION=$(echo ${GITHUB_REF:11})" >> "$GITHUB_ENV"
          echo "BUILD_VERSION_LATEST=latest" >> "$GITHUB_ENV"

      - name: Build and tag app
        run: docker build -t $IMAGE_NAME:$BUILD_VERSION -t $IMAGE_NAME:$BUILD_VERSION_LATEST --build-arg BUILD_VERSION=${BUILD_VERSION} -f docker/app/Dockerfile .
        env:
          IMAGE_NAME: sillsdev/web-languageforge

      - name: Reveal images
        run: docker images

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish all tagged images to Docker Hub
        run: |
          docker push -a sillsdev/web-languageforge
