name: Deploy to staging

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - chore/refactor-actions

jobs:
  full-ci-cd:
    runs-on: ubuntu-latest

    env:
      IMAGE: sillsdev/web-languageforge

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Build app
        working-directory: ./docker/
        run: docker-compose build --build-arg ENVIRONMENT=production app
      -
        name: Check unit tests
        working-directory: ./docker/
        run: make unit-tests
      # -
      #   name: Check e2e tests
      #   working-directory: ./docker/
      #   run: make e2e-tests
      -
        name: Tag images
        run: docker tag lf-app ${{ env.IMAGE }}:develop-$(date +%Y%m%d)-${{ github.sha }}
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Publish image
        run: docker push ${{ env.IMAGE }}
