# delete the old prod job when done, might need to change this name if we paramterize the workflow
name: Deploy to production

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      # TODO: temp for development, remove when ready to deploy to production, should be triggering off of a tag.
      - 'chore/issue-1279-implement-cd-for-prod'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      IMAGE: ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Build app
        working-directory: ./docker/
        # TODO: send in the build arg for cache-busting, remove ENVIRONMENT if the Dockerfile builds that way by default (just ensure it's development in the docker-compose file)
        run: echo build # TODO: bring back in after testing: docker-compose build --build-arg ENVIRONMENT=production app
      -
        name: Check unit tests
        working-directory: ./docker/
        run: echo run unit tests # TODO: bring back in after testing: make unit-tests
      # -
      #   name: Check e2e tests
      #   working-directory: ./docker/
      #   run: make e2e-tests
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        # TODO: this needs to move above build line since some of it is needed for the build, it also needs to be changed to use the tag.
        name: Establish image name
        id: image
        run: |
          echo ::set-output name=NAMESPACE::sillsdev/web-languageforge
          echo ::set-output name=TAG::develop-$(date +%Y%m%d)-${{ github.sha }}
      -
        name: Tag images
        run: echo ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }} # TODO: bring back in after testing: docker tag lf-app ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}
      -
        name: Publish image
        run: echo ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }} # TODO: bring back in after testing: docker push ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}

  deploy:
    runs-on: [self-hosted, languageforge]

    needs: build

    steps:
      -
        # TODO: bring back in after testing: uses: sillsdev/common-github-actions/install-kubectl@v1
      -
        # TODO: this needs to be changed to production context (and possibly parameterized so there's only one deploy workflow...)
        run: echo ${{ secrets.LTOPS_K8S_STAGING_CONTEXT }}:${{ needs.build.outputs.IMAGE }} # TODO: bring back in after testing: kubectl --context ${{ secrets.LTOPS_K8S_STAGING_CONTEXT }} set image deployment/app app=${{ needs.build.outputs.IMAGE }}
