name: Deploy to staging

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      IMAGE: ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Build app
        working-directory: ./docker/
        run: docker-compose build --build-arg ENVIRONMENT=production app
      -
        name: Check unit tests
        working-directory: ./docker/
        run: make unit-tests
      # -
      #   name: Check e2e tests
      #   working-directory: ./docker/
      #   run: make e2e-tests
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Establish image name
        id: image
        run: |
          echo ::set-output name=NAMESPACE::sillsdev/web-languageforge
          echo ::set-output name=TAG::develop-$(date +%Y%m%d)-${{ github.sha }}
      -
        name: Tag images
        run: docker tag lf-app ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}
      -
        name: Publish image
        run: docker push ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG }}

  deploy:
    runs-on: [self-hosted, languageforge]

    needs: build

    steps:
      -
        name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version
      -
        name: Deploy to staging
        run: kubectl --context ${{ secrets.LTOPS_K8S_STAGING_CONTEXT }} set image deployment/app app=${{ needs.build.outputs.IMAGE }}
