name: Run E2E tests

on:
  workflow_call:

jobs:
  e2e-tests:
    name: ${{matrix.browser}} (${{ matrix.shard }}/${{ matrix.shards }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox]
        shard: [1, 2, 3, 4, 5, 6]
        shards: [6]

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Playwright E2E Tests
        run: make e2e-tests-ci browser=${{ matrix.browser }} shard="${{ matrix.shard }}/${{ matrix.shards }}"
      -
        name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.browser }}-${{ matrix.shard }}
          path: test/e2e/test-results
          if-no-files-found: error

  e2e-tests-result:
    if: always()
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Check aggregated E2E result
        if: ${{ needs.e2e-tests.result != 'success' }}
        run: |
          echo "Some E2E tests failed"
          exit 1
