name: Run E2E Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: docker

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Run E2E Tests
        run: make e2e-tests
