name: Integrate changes and deploy

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - bugfix/cache-buster

jobs:
  integrate:
    runs-on: ubuntu-latest

    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      -
        uses: actions/checkout@v3
      -
        run: |
          docker --version
          docker compose version
      -
        name: Establish image name
        id: image
        run: |
          echo "NAMESPACE=sillsdev/web-languageforge" >> $GITHUB_OUTPUT
          echo "TAG_APP=GOVOLS" >> $GITHUB_OUTPUT
      -
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: 'npm'
      -
        run: npm ci
      -
        name: Build legacy app
        run: docker compose build --build-arg ENVIRONMENT=production --build-arg BUILD_VERSION=${{ steps.image.outputs.TAG_APP }} app
      -
        name: Verify version stamping
        run: |
          docker compose run --rm app cat build-version.txt version.php
          docker compose run --rm app cat version.php | grep ${{ steps.image.outputs.TAG_APP }}
      -
        name: Tag images
        run: |
          docker tag lf-app ${{ steps.image.outputs.NAMESPACE }}:${{ steps.image.outputs.TAG_APP }}
      -
        run: docker images
