name: Deploy to production

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - v*

jobs:
  production:
    if: github.event.base_ref == 'refs/heads/master'

    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_iduses
    uses: sillsdev/web-languageforge/.github/workflows/integrate-and-deploy.yml@master
    with:
      image-tag-app: $(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
      image-tag-proxy: next-proxy-$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
      image-tag-next-app: next-app-$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')

    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecrets
    secrets:
      kube-context: ${{ secrets.LTOPS_K8S_PRODUCTION_CONTEXT }}
      image-repo-username: ${{ secrets.DOCKERHUB_USERNAME }}
      image-repo-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
