name: Build and Test

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Unit Tests
        run: make unit-tests-ci
      -
        name: Publish Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v2
        if: always()
        with:
          check_name: Unit Test Results
          github_token: ${{ github.token }}
          junit_files: PhpUnitTests.xml

  build-app-run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
          cache: 'npm'
      -
        name: Get installed Playwright version
        id: playwright-version
        run: echo -n "version=$(npm ls @playwright/test --json | jq --raw-output '.version')" >> $GITHUB_OUTPUT
      -
        name: Cache playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          # Make each playwright version use its own cache in case it uses different browser versions
          # Cache entries are deleted if not accessed for 7 days
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
          key: 'playwright-${{ steps.playwright-version.outputs.version }}'

      -
        name: Playwright E2E Tests
        # see https://playwright.dev/docs/ci#github-actions
        run: make playwright-tests-ci

      -
        name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results

  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"
          cache: "npm"
      -
        name: Run prettier check
        run: npx prettier --check .

  # protractor-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     -
  #       uses: actions/checkout@v3
  #     -
  #       name: Build app
  #       run: make build
  #     -
  #       name: Run E2E Tests
  #       run: make e2e-tests-ci
  #     -
  #       name: Publish Test Results
  #       uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
  #       if: always()
  #       with:
  #         check_name: E2E Test Results
  #         github_token: ${{ github.token }}
  #         files: docker/e2e-results.xml
