name: Build and Test

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  require-label:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - uses: mheap/github-action-required-labels@5847eef68201219cf0a4643ea7be61e77837bbce # v5.4.1
        id: check-labels
        with:
          mode: exactly
          count: 1
          labels: "bug, feature, engineering, security fix, testing"
      - uses: mheap/github-action-required-labels@5847eef68201219cf0a4643ea7be61e77837bbce # v5.4.1
        with:
          mode: exactly
          count: 0
          labels: "do not merge"

  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      -
        uses: actions/checkout@v4
      -
        name: Unit Tests
        run: make unit-tests-ci
      -
        name: Publish Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v2
        if: always()
        with:
          check_name: Unit Test Results
          github_token: ${{ github.token }}
          junit_files: PhpUnitTests.xml

  e2e-tests:
    uses: ./.github/workflows/e2e-tests.yml

  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: pnpm/action-setup@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"
          cache: "pnpm"
      -
        name: Run prettier check
        run: |
          pnpm dlx prettier -v
          pnpm dlx prettier --check .
