name: Build and Test

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: docker

env:
  DOCKER_BUILDKIT: 1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Unit Tests
        run: make unit-tests-ci
      -
        name: Publish Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with:
          check_name: Unit Test Results
          github_token: ${{ github.token }}
          files: docker/PhpUnitTests.xml

  build-app-run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'npm'
      -
        name: Build app
        run: |
          npm ci
          docker-compose build app
      - name: Get installed Playwright version
        id: playwright-version
        # https://github.com/microsoft/playwright/issues/7249#issuecomment-1201476980
        run: echo -n "::set-output name=version::$(npm ls @playwright/test --json | jq --raw-output '.dependencies["@playwright/test"].version')"

        # https://github.com/microsoft/playwright/issues/7249#issuecomment-1154603556
      - name: Cache playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          # Make each playwright version use its own cache in case it uses different browser versions
          # Cache entries are deleted if not accessed for 7 days
          # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
          key: 'playwright-${{ steps.playwright-version.outputs.version }}'

      - name: Playwright E2E Tests
        working-directory: .
        # see https://playwright.dev/docs/ci#github-actions
        run: npm run make playwright-tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  # protractor-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     -
  #       uses: actions/checkout@v2
  #     -
  #       name: Build app
  #       run: make build
  #     -
  #       name: Run E2E Tests
  #       run: make e2e-tests-ci
  #     -
  #       name: Publish Test Results
  #       uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
  #       if: always()
  #       with:
  #         check_name: E2E Test Results
  #         github_token: ${{ github.token }}
  #         files: docker/e2e-results.xml
