name: Build and Test

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: docker

env:
  DOCKER_BUILDKIT: 1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Unit Tests
        run: make unit-tests-ci
      -
        name: Publish Test Results
        uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
        if: always()
        with:
          check_name: Unit Test Results
          github_token: ${{ github.token }}
          files: docker/PhpUnitTests.xml

  build-app-run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'npm'
      -
        name: Build app
        run: |
          npm ci
          docker-compose build app
      # -
      #   name: Playwright E2E Tests
      #   working-directory: .
      #   # see https://playwright.dev/docs/ci#github-actions
      #   run: |
      #     docker-compose -f docker/docker-compose.yml up -d app-for-playwright
      #     npx playwright install
      #     npx playwright test

  # protractor-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     -
  #       uses: actions/checkout@v2
  #     -
  #       name: Build app
  #       run: make build
  #     -
  #       name: Run E2E Tests
  #       run: make e2e-tests-ci
  #     -
  #       name: Publish Test Results
  #       uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
  #       if: always()
  #       with:
  #         check_name: E2E Test Results
  #         github_token: ${{ github.token }}
  #         files: docker/e2e-results.xml
