name: Deploy to staging

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - develop

    # TODO: remove this trigger before merging into `develop`
    tags:
      - next-app-staging

jobs:
  staging:
        # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_iduses
        # uses: sillsdev/web-languageforge/.github/workflows/integrate-and-deploy.yml@develop
        # TODO: remove this targeted call before merging into `develop`
        uses: sillsdev/web-languageforge/.github/workflows/integrate-and-deploy.yml@next-app-staging
        with:
          image-tag-app: develop-$(date +%Y%m%d)-${{ github.sha }}
          image-tag-proxy: next-proxy-$(date +%Y%m%d)-${{ github.sha }}
          image-tag-next-app: next-app-$(date +%Y%m%d)-${{ github.sha }}
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecrets
        secrets:
          kube-context: ${{ secrets.LTOPS_K8S_STAGING_CONTEXT }}
          image-repo-username: ${{ secrets.DOCKERHUB_USERNAME }}
          image-repo-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}


# VERSION_APP=develop-20220321-1ff79ed4ff4363d40e07ecff3d5e6eb9f12bdaee
# VERSION_PROXY=next-proxy-20220329-ce962fb24668319b69575fe37ceed0d8667b1e9a
# VERSION_NEXT_APP=next-app-20220329-ce962fb24668319b69575fe37ceed0d8667b1e9a make deploy-staging
