name: Deploy to staging

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      #TODO: revert this when done testing - develop
      - chore/issue-1279-implement-cd-for-prod

jobs:
  staging:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_iduses
      # TODO: update the branch appropriately
      uses: sillsdev/web-languageforge/.github/workflows/integrate-and-deploy.yml@chore/issue-1279-implement-cd-for-prod
      with:
        image-tag: develop-$(date +%Y%m%d)-${{ github.sha }}
        kube-context: ${{ secrets.LTOPS_K8S_STAGING_CONTEXT }}
