name: Run unit tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  pull_request:

  push:
    branches:
      - develop
      - staging

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        working-directory: ./docker/
        run: make unit-tests

